import '@fontsource-variable/outfit';
import '@fontsource/noto-sans-jp/500.css';
import '@fontsource/noto-sans-jp/800.css';
import { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Lyle Vince Dela Cuesta | Web Developer',
  description: 'Generated by create next app',
  icons: {
    icon: { url: '/favicon.svg', type: 'image/svg' },
    shortcut: { url: '/favicon.svg', type: 'image/svg' },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className='bg-white text-black dark:bg-black dark:text-white'>{children}</body>
    </html>
  );
}
